# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "charge_transactions", :force => true do |t|
    t.column "description", :string
    t.column "created_at",  :date
  end

  create_table "charges", :force => true do |t|
    t.column "transaction_id", :integer
    t.column "creditor_id",    :integer
    t.column "debtor_id",      :integer
    t.column "amount",         :float
  end

  create_table "chore_groups", :force => true do |t|
    t.column "name",                    :string
    t.column "description",             :text
    t.column "initial_assignee_id",     :integer
    t.column "initial_assignment_time", :datetime
  end

  create_table "chores", :force => true do |t|
    t.column "name",             :string
    t.column "description",      :text
    t.column "frequency_amount", :integer
    t.column "frequency_unit",   :string
  end

  create_table "chores_chore_groups", :id => false, :force => true do |t|
    t.column "chore_id",       :integer
    t.column "chore_group_id", :integer
  end

  create_table "housemates", :force => true do |t|
    t.column "person_id", :integer
  end

end
